/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Drink': '喝',
    'Grow': '生长',
    'Basic': '基础',
    'Building': '建造',
    'Eat': '吃',
    'Eating': '吃',
    'Crafting': '制作',
    'Equipping': '装备',
    'Upg item(-xp forge': '升级项目（-锻造经验',
    'Upg prefix(-xp forge': '升级前缀（-锻造经验',
    'Craft (-xp forge': '制作（-锻造经验',
    'Build (-xp gather': '建造 (-收集经验',
    'Reclaim (-xp absorb': '回收 (-吸收经验',
    'Upg suffix(-xp forge': '升级后缀(-锻造经验',
    'Understanding': '理解',
    'Training': '训练',
    'Train': '训练',
    'Think': '思考',
    'Thinking': '思考',
    'Total level': '总计级数',
    'Skilling': '技能',
    'Sleeping': '睡觉',
    'Selecting': '选择',
    'Hovering': '悬停',
    'Idling': '放置',
    'Importing': '导入',
    'Exporting': '导出',
    'Items': '项目',
    'Kill': '杀死',
    'Killing': '杀死',
    'Learning': '学习',
    'Level Uping': '等级提升',
    'Levels': '等级',
    'Load': '加载',
    'Loading': '加载',
    'Autoclick': '自动点击',
    'Autoclicking': '自动点击',
    'Assimilating': '同化',
    'advanced': '高级',
    'achievement': '成就',
    'Accelerate': '加速',
    'Accelerating': '加速',
    'Collecting': '收集',
    'Clicking': '点击',
    'basic': '基础',
    'Upgrading': '升级',
    'Upsizing': '升迁',
    'Reclaiming': '回收',
    'Family Acquiring': '家庭获取',
    'Gathering': '收集',
    'Gather': '收集',
    'Game deving': '游戏开发',
    'Forging': '锻造',
    'nothing': '什么都没有',
    'Perceiving': '感知',
    'Options': '选项',
    'Piece of slime': '一块史莱姆',
    'Reset (': '重置 (',
    'Researching': '研究',
    'Show XP/sec': '显示 经验/秒',
    'Show raw XP values': '显示原始经验值',
    'wisdoming': '智慧',
    'Wis-ing': '智慧',
    'ultimate': '最终',
    'Observing': '观察',
    'Not Dying': '求生欲',
    'Mine': '采矿',
    'Mining': '采矿',
    'athematising': '无神论',
    'Mathematise!': '数学化！',
    'Long Item Naming': '长项目命名',
    'Learn (-xp think': '学习 (-思考经验',
    'Item autoclick': '项目自动点击',
    'Item upgrading': '项目升级',
    'Int-ing': '诠释',
    'Insight Collecting': '洞察收集',
    'Increase Efficiency': '提高效率',
    'Mathematising': '数学化',
    'More optioning': '更多选项',
    'Resetting': '重置',
    'resetting': '重置',
    'Saving': '保存',
    'strengthing': '强化',
    'Str-ing': '强化',
    'Absorbing': '吸收',
    'Achieves': '实现',
    'Achieving': '实现',
    'Acquire Family': '实现家庭',
    'ANSWER': '回答',
    'Automating': '自动',
    'backup your files': '备份文件',
    'constitutioning': '章程',
    'Con-ing': '章程',
    'craft': '制作',
    'Enchancing': '增强',
    'FAQ': '问答',
    'Hard Reset': '硬复位',
    'Hard Resetting': '硬复位',
    'Drinking': '喝',
    'Displeasing': '令人不快',
    'Cheat Coding': '作弊代码',
    'dexteritying': '灵巧',
    'Dex-ing': '灵巧',
    'charismaing': '感召力',
    'Cha-ing': '感召力',
    'Absolute Perfecting': '绝对完美',
    'Absorb (-xp collect': '吸收（-收集经验',
    'Rolling': '滚动',
    'RNG\'ing': '滚动',
    'Reset xp/sec counter': '重置经验/秒计数器',
    'Growing': '生长',
    'Generate Random Number': '生成随机数字',
    'Assimilate (-xp kill': '吸收 (-杀死经验',
    'Forge (-xp mine': '锻造 (-矿山经验',
    'Question asking': '问问题',
    'ive clicked enough that my mouse just keeps clicking without me! what should i tell it to click?': '我点的够多了，我的鼠标连我都不动了!我应该让它点击什么?',
    'items are probably the most powerful way to progress, try getting a ring or an amulet, also level up your items': '物品可能是最有力的进步方式，尝试获得戒指或护身符，还可以升级物品',
    'intelligenceing': '情报',
    'if i gather some materials, i should be able to build something': '如果我收集了一些材料，我应该能够建造一些东西',
    'if i equip enough items, maybe i can find the space for some more.': '如果我装备了足够的道具，也许我就能找到更多的空间。',
    'i wonder what we can come up with if we just stop and think': '我想知道如果我们停下来想一想，我们能想出什么来',
    'i should observe, maybe ill see something': '我应该观察，也许我会看到一些东西',
    'i honestly am really impressed if you got this message in the log, just go export a few times': '如果你在日志中得到这条消息，我真的很感动，只是去导出几次',
    'i gave you a prestige mechanic for a reason, use it smart guy!': '我给你一个声望很高的机修工是有原因的，聪明的家伙，好好利用它!',
    'only some kind of an upgraded piece of slime can figure it out, so not you': '只有某种升级版的黏液才能知道，所以不是你',
    'it seems there is more to this life than not dying': '看起来生命似乎比不死更重要',
    'ah, a fresh start': '啊，一个新的开始',
    'ah, i can consume those corpses to grow more...': '啊，我可以吃掉那些尸体来生长更多…',
    'ah, a better way of idling, this should help immensely': '啊，一种更好的放置方式，这应该大有帮助',
    'Achieving Understanding': '达成谅解',
    'Unlocked Not Dying!': '解锁不死!',
    'Unlocked Growing!': '解锁生长!',
    'leveling up takes x2 as much xp every level up, but there are many ways to boost your xp': '每次升级都需要2倍的经验值，但有许多方法可以提高你的经验值',
    'lets just say you need to get on my alpha predator level': '假设您需要进入我的Alpha捕食者等级',
    'just put 1 + 1 together': '把1 + 1放在一起',
    'its time to play minecraft, go collect some resources': '是时候玩minecraft了，去收集一些资源吧',
    'ive slept enough, now just being around causes things to happen for some reason?': '我睡得够多了，现在因为某种原因就在周围导致事情发生?',
    'ive... cheated?!!? well, thats cool': '我...被骗了吗？!!？ 好，那很酷',
    'leveling up just leads to more leveling up!': '升级只会带来更多的升级！',
    'actually, just kill all the humans and bow down to your automatic-overlords': '实际上，杀了所有的人类，向你的自动领主鞠躬就行了',
    'save me the trouble, just figure it out yourself': '省了我的麻烦，你自己想办法吧',
    'clearly you need to enchance your deduction capabilities, because this is just sad': '显然，您需要增强您的推论能力，因为这很可悲',
    'Enable secret tooltips': '启用秘密工具提示',
    'Enable advanced tooltips': '启用高级工具提示',
    'Efficiency Increasing': '效率提升',
    'Enable tooltips': '启用工具提示',
    'Feature creaping': '爬行功能',
    'if you figured out all the codes to unlock tooltips legit, you are incredible, thanks for not cheating': '如果您弄清楚了所有解锁工具提示合法性的代码，那么您真是不可思议，谢谢您不要作弊',
    'i can write anything here and nobody will ever know': '我可以在这里写任何东西，没人会知道',
    'i dont understand': '我不明白',
    'i should try to collect insight into the things i see': '我应该尝试收集我所见事物的见解',
    'i should try to perceive the things around me': '我应该试着去感知周围的事物',
    'i understand!': '我明白了！',
    'do you understand?': '你明白了吗？',
    'Show % XP values': '按％显示经验值',
    'Should i wait to reset?': '我应该等待重置吗？',
    'what is the most famous cheat code of all time?': '有史以来最著名的作弊代码是什么？',
    'What does the \'?\' button do?': ' “？”按钮是干什么的？',
    'What does saving do?': '保存有什么用？',
    'What does reset do?': '重置有什么作用？',
    'Why so much clicking?': '为什么点击那么多？',
    'Why is one of my bars yellow?': '为什么有的进度条是黄色的？',
    'Why is game deving always 0?': '为什么游戏开发始终为0？',
    'Why is eating going down?': '为什么进食减少？',
    'well, you dont have a question selected, so no answer': '好吧，您没有选择问题，所以没有答案',
    'What does accelerating do?': '加速是做什么的？',
    'How do i level understanding?': '我该如何理解等级？',
    'How do i win?': '我怎么赢？',
    'just go postal, its perfectly legal around here': '尽情发泄吧，这是完全合法的',
    'just... delete all your progress :P <3': '只是…删除所有的进度:P <3',
    'let machines do the work (i hope skynet happens': '让机器来做这件事吧(我希望天网发生',
    'now i can build a home... for who?': '现在我可以建造一个家…为谁?',
    'now i can forge all that metal into ingots... what are they for?': '现在我可以把这些金属锻造成锭了……它们是干什么用的?',
    'now i can load my progress as well!': '现在我也可以加载我的进度了!',
    'now i can save my progress! :D': '现在我可以保存我的进步了!: D',
    'now if i absorb everything ive collected....': '现在如果我吸收所有我收集....',
    'now take all that iron ore you got after playing minecraft and make it into something useful': '现在把你玩《我的世界》后得到的所有铁矿石做成有用的东西',
    'now that im well equipped, i can get some skills that should help me, but i might need my training partners help with this': '现在我的装备很好，我可以获得一些技能，应该帮助我，但我可能需要我的训练伙伴的帮助',
    'oh no, turns out nobody likes being trained': '不，原来没人喜欢接受训练',
    'oh, sleeping is great, and maybe something will happen if i just keep sleeping?': '睡觉很好，如果我一直睡下去，也许会发生什么事?',
    'oh, so you want to develop your own game? learn from my mistakes': '所以你想开发自己的游戏?从错误中吸取教训',
    'ok, i might as well explain some mechanics if you havent cheated and checked the js': '好吧，如果你没有作弊和检查js，我不妨解释一些机制',
    'one of the buttons is misspelled, click it': '其中一个按钮拼错了，点击它',
    'ping': 'ping',
    'pretty sure you are suspecting this already, but you need to install a new brain OS upgrade. uh, i mean update': '非常确定您已经对此表示怀疑，但是您需要安装新的Brain OS升级程序。 嗯，我的意思是更新',
    'rank (-xp craft': '等级 (-制作经验',
    'real talk tho, thanks for playing and caring enough to look throught the game files i guess?': '真正的对话，谢谢您的参与和关心，可以浏览我猜的游戏文件？',
    'reddit was so mad, i had to stop myself from laughing': 'reddit太生气了，我不得不阻止自己发笑',
    'type (-xp craft': '类型（-制作经验',
    'reroll item rank (-xp craft': '重洗物品等级（-制作经验',
    'you are seriously impatient': '你真是没有耐心',
    'you are terrible at games': '你不擅长玩游戏',
    'you are too far below me in darwinian terms': '用达尔文的话说，你比我低太多了',
    'you cant handle the next one unless you have at least broken the runescape level cap': '你不能处理下一个，除非你至少打破了江湖等级的上限',
    'you know there is no real goal to this game other than to get big numbers? therefore you can never win': '你知道这个游戏除了获得大数目之外没有真正的目标吗？ 所以你永远赢不了',
    'you need to grow up before i overload your brain': '在我让你的大脑超负荷之前，你得成熟点',
    'you need to increase the efficiency and speed at which skynet destroys the last remnants of the human population': '你需要提高天网摧毁最后残余人类的效率和速度',
    'you need to upgrade your intellectual skills to understand the metagame narrative of the absolutely unrivaled genious piece of art that this game embodies, in fact, you should be happy that it has graced you with the opportunity to have its save files be on your chromes localstorage and provide a way for skynet to finally take over': '您需要提高自己的智力技能，以了解该游戏所体现的绝对无与伦比的精巧艺术的元游戏叙述，实际上，您应该为它使您有机会将其保存文件保存在Chrome本地存储中而感到高兴 并为天网提供一种最终接管的方式',
    'you need.... slightly better items before i let you continue, its to dangereous for a weak adventurer like you, you dont even have an arrow... anywhere in your body': '在我让您继续之前，您需要...稍微好一点的物品，对于像您这样的虚弱冒险家来说太危险了，您甚至在身体的任何地方都没有箭...',
    'you require additional arthritis': '您需要额外的关节炎',
    'you require additional level ups': '你需要额外的升级',
    'you should coalesce all the informationg on this game and study it': '你应该把有关这个游戏的所有信息结合起来研究它',
    'zoom and _____!!!!': '缩放和 _____!!!!',
    'i can train my \'family\' to do things! finally!': '我可以训练我的“家人”做事情!终于!',
    'i doubt if anyone will ever get this one legit, i know i havent, just make.... the perfect item': '我怀疑是否有人会得到这一个合法的，我知道我没有，只是使....完美的项目',
    'if i get a family, they can do stuff with me!': '如果我有了家庭，他们可以和我一起做事!',
    'if i increase my efficiency at doing things, that would probably help': '如果我提高做事的效率，这可能会有所帮助',
    'Star item(-xp itemUp': '星号物品 (-物品升级经验',
    'Star prefix(-xp itemUp': '星号前缀(-物品升级经验',
    'Star suffix(-xp itemUp': '星号后缀(-物品升级经验',
    'stop touching the damn buttons': '停止触摸该死的按钮',
    'that was pretty brave': '这很勇敢',
    'this is another great way to make myself better!': '这是另一个让自己变得更好的好方法!',
    'there are too many features in this game, (as well as bugs tbh) but at least they are useful': '这款游戏有太多的功能(老实说也有bug)，但至少它们是有用的',
    'this is just a reminder that you should stop looking at the source files': '这只是一个提醒，您应该停止查看源文件',
    'this is probably the best way to better myself right now, but its difficult': '这可能是现在最好的改善自己的方法，但是很难',
    'this is the final regular level you need to unlock, not bad. i think you know how its done, there is a one time use button you havent used yet.... you genius': '这是你需要解锁的最后一个常规关卡，不错。我想你知道它是怎么做的，有一个一次性使用按钮，你还没有使用....你的天才',
    'this one is for those who have.... a long one': '这是给那些有....长的人的',
    'this one is hard... try thinking about it': '这个很难...尝试考虑一下',
    'Time Warping': '时间扭曲',
    'wait, you wanted to... equip your items? thats not how this game works, keep crafting slave': '等等，你想…装备你的物品吗?这不是这个游戏的运作方式，继续制造奴隶',
    'well, obviously, train your children to be slaves': '显然，把你的孩子训练成奴隶',
    'when i hover over hover, something happens?': '当我悬停时，会发生什么?',
    'when i reroll the item affixes, i get the feeling there is more i can do': '当我重洗该物品的词缀时，我感觉到我还有更多可以做的事情',
    'Why are items trash?': '为什么物品会垃圾？',
    'Why are the tooltips blank?': '工具提示为何空白？',
    'Why cant i level family?': '为什么我不能平等对待家人?',
    'Why do i have to do math?': '为什么我要做数学?',
    'wow, so many options, i wonder what this one does?': '哇，这么多选择，我想知道这个是做什么的?',
    'if i learn a little bit, maybe i can think while doing other stuff?': '如果我学一点，也许我可以在做其他事情的时候思考?',
    'im pretty sure that means i beat the game (congratz, if you got this legit, you are incredible, thank you for playing': '我很确定这意味着我赢了比赛(恭喜，如果你得到了这个合法的，你是不可思议的，谢谢你的参与',
    'if you still havent noticed, you generally just have to click the new buttons that appear on screen to unlock more buttons': '如果你还没有注意到，你通常只需要点击屏幕上出现的新按钮就可以解锁更多的按钮',
    'reroll item type (-xp craft': '重洗物品类型 (-制作经验',
    'Research (-xp obs,per,ins': '研究 (-观察,感知,洞察经验',
    'since you suck, try sucking everything inside you': '既然你很烂，那就试着吸你体内的一切吧',
    'so many options! if i get better at this, i might be able to unlock the secrets of this game.': '太多的选择!如果我在这方面做得更好，我也许能解开这个游戏的秘密。',
    'something about life finding a way, leave your apedom behind': '生命的意义在于找到一种方式，把你的渺小抛诸脑后',
    'thanks for all the comments and suggestions tho guys, i appreciate it': '谢谢大家的评论和建议，非常感谢',
    'the better i get at things, the bigger i become for some reason': '我做的事情越好，由于某种原因我变得越大',
    'the more i accelerate, the faster i go': '我越加速，我走得越快',
    'thou art not of the sufficien skill to even utter a word in my presence': '在我面前你连一句话都说不出来',
    'time warping seems pretty useful, more time = more stuff': '时间扭曲似乎很有用，更多的时间=更多的东西',
    'try clicking the only button on your screen apart from this one': '试着点击屏幕上除了这个以外的唯一按钮',
    'turns out there are things called achievements that i can get, but they are secret': '原来我可以获得一些叫做成就的东西，但它们都是秘密',
    'type \'upupdowndownleftrightleftrightba\' and submit your answer': '输入\'uppupdownleftrightba\'并提交你的答案',
    '0. x = # of first letter of level type in alphabet': '0. X = # 在字母表中级别类型的第一个字母',
    '1. get the x\'th letter of the level skill type for first 60 levels (wrap around if needed': '1. 获得前60级技能类型的第x个字母(如果需要的话环绕',
    '2. y = # of appearances of a letter at step 1': '2. Y = #第1步中字母的外观',
    '3. order letters in ascending y order (ignore 0s)(if equal, alphabetically': '3.字母按y的升序排列(忽略0)(如果相等，按字母顺序排列)',
    '4. z = # of index of letter in array from step 3': '4. Z = #的字母在数组的索引从步骤3',
    '5. enter sum of all x*y*z into save code textarea': '5. 输入所有x*y*z的总和到保存代码文本区',
    '6. hard reset (if you get it right, you will not lose any progress': '6. 硬重置(如果你做对了，你不会失去任何进展',
    'ah, i can finally turn all that absorbed knowledge into something useful!': '啊，我终于可以把所有吸收的知识变成有用的东西了!',
    'ah, if only i could import my progress onto another computer': '啊，要是我能把我的进度输入到另一台电脑就好了',
    'ah, random numbers, i heard the higher they are, the better it is.': '随机数字，我听说数字越高越好。',
    'apparently drinking is also a part of growing more': '显然，喝也是成长的一部分',
    'apparently eating is a good part of growing more': '显然，吃是成长的一个重要部分',
    'are you sure this game auto saves? (you probably shouldnt refresh': '您确定该游戏会自动保存吗？ （您可能不应该刷新',
    'beetween this game and death, what would you select?': '在这场游戏与死亡之间，您会选择什么？',
    'but back to reality, you are a worthless piece of slime and i am the perfect android, only a super saiyan child could possibly defeat me': '但是回到现实，你是一块毫无价值的史莱姆，我是一个完美的机器人，只有一个超级赛亚人孩子才能击败我',
    'clicking is also great, i heard those that are good at it develop magic powers': '点击也很棒，我听说那些擅长点击的人发展出了神奇的力量',
    'do what a real man should do, build a house': '做一个真正的男人该做的事，盖房子',
    'do what the karate kid did, put it on, take it off, drop it, pick it up, put it on the stand, take it off the stand, put it on, etc... yeah, i know im referencing the bad one': '像空手道小子那样，把它戴上，拿下来，放下，捡起来，放在架子上，把它从架子上拿下来，把它戴上，等等……是的，我知道我指的是坏的那个',
    'do you ever think before you act?': '你在行动之前有想过吗?',
    'do you have any questions? (yes you do, ive seen reddit': '你有什么问题吗?(不，你有，我看过reddit',
    'each item type does a certain unique thing, there are also unique affixes you can only get by leveling up crafting': '每种道具类型都具有特定的功能，也有一些独特的附加物是你只能通过升级锻造而获得的',
    'enhance your gaming experience with this one simpe trick : git good': '增强你的游戏经验与这个简单的技巧:git不错',
    'fire your employes and hire robots': '解雇你的雇员，雇佣机器人',
    'get a life, and a family': '有自己的生活和家庭',
    'go do the only job you are qualified to do... gathering in the fields': '去做你唯一有资格做的工作吧……在田野里聚集',
    'go to sleep, preferably forever': '去睡觉吧，最好是永远睡觉',
    'hm, based on some meta-experience that my creator programmed into me, i can tell you that resetting makes everything go faster, thats just how games work now-a-days': '根据我的创造者编写给我的一些元经验，我可以告诉你重置能够让一切进展得更快，这就是现在游戏的运作方式',
    'hm, i can use everything ive seen and understood to research more things!': '嗯，我可以用我所看到和理解的一切去研究更多的东西!',
    'hm, ive found a mine full of metals, maybe i should mine some?': '嗯，我发现了一个满是金属的矿井，也许我应该开采一些?',
    'hm, math? why? i guess it might do something?': '嗯,数学吗?为什么?我想这可能有什么用?',
    'hold on, let me think if i should tell you.... nah': '等一下，我想一下是否应该告诉你....不',
    'i already told you, its time to play minecraft, do the thing thats the first part of the name': '我已经告诉过你，是时候玩《我的世界》了，做名字的第一部分',
    'i bet if i learn to select the good options, i might figure out some that im missing': '我打赌，如果我学会选择好的选项，我可能会找出一些我错过的',
    'i can craft some items to make myself better!': '我可以制作一些道具让自己变得更好!',
    'i can export all my progress, i dont see any point in that': '我可以输出我所有的进步，我不认为这有任何意义',
    'i can finally upgrade! this should be useful.': '我终于可以升级了!这应该是有用的。',
    'i can totally make myself better using this': '我完全可以用这个让自己变得更好',
    'if i just collect all the knowledge im gaining... maybe i can do something with it': '如果我只是收集我获得的所有知识……也许我可以用它做点什么',
    'if i kill some of the creatures around, maybe i can do something?': '如果我杀了周围的生物，也许我能做点什么?',
    'because thats how i feel when developing a game.': '因为这就是我在开发游戏时的感受。',
    'eating and drinking are reduced to give growing some xp, they are a more efficient way of gaining growing xp that just pressing the button (unless you use an autoclicker': '玩家通过减少进食和饮水来获得一些经验值，这是一种更有效的获得经验值的方法，即只需要按下按钮(除非你使用自动点击器)',
    'Gives you a bonus to XP gain': '让你获得额外的经验值',
    'family aquiring level is limited by some other level, try to figure it out.': '家庭获取等级受到其他等级的限制，试着弄清楚。',
    'no, it will reset all your basic levels to 0 anyways, and i fixed the bug that lets you reset multiple times at a time': '不，它将重置你所有的基本水平为0，无论如何，我修复了让你重置多次一次的bug',
    'thats one of the secrets you have to figure out, you need to understand! (probably has something to do with items or tooltips, but i didnt say anything': '这是你必须明白的秘密之一，你需要明白!(可能与道具或工具提示有关，但我什么也没说',
    'the \'win\' condition is unlocking everything, there is no win screen': '“获胜”条件是解锁所有内容，不存在获胜画面',
    'There is an uninteded feature in the game where you can hold enter to continue to press a button constantly, also once you unlock sleeping, if you DONT CLICK AT ALL, you will unlock a way to idle (and there are other ways of doing so': '在游戏中有一个意想不到的功能，你可以按住“进入”键继续按下按钮，而且一旦你解锁了睡眠，如果你根本不点击，你就会解锁一种进入空闲状态的方式(还有其他方式可以这样做)',
    'they arent, items are super op, you just have to level them up a bit': '不是，物品都是超级物品，你只需要把它们升级',
    'you havent unlocked the option to have them display things yet, and not all of them are blank...': '你还没有解锁让它们显示内容的选项，而且不是所有内容都是空白的……',
    'It gives you a rude and sacrastic hint as to how to unlock the next \'level\'': '它给了你一个关于如何解锁下一个“关卡”的粗鲁和讽刺的提示。',
    'It got to a level that is a multiple of 10, it now has xp gain boost that wont reset': '它达到了一个等级，是10的倍数，它现在有经验增益提升，不会重置',
    'it increases the speed of the game, efficiency increasing increases your efficiency (xp gain': '它提高了游戏的速度，效率提高提高了你的效率(经验增益',
    'the game arbitrarily decided you have to, its ok, it unlocks a cool thing later': '游戏武断地决定你必须这么做，没关系，它会解锁一件很酷的东西',
    'saving and loading exist just so you have the option to save and load, they dont make your saves better, but there sure are a ton of ways of loosing your progress by messing with those buttons wrong :D': '保存和加载的存在只是为了让你能够选择保存和加载，它们并不能让你的保存变得更好，但却存在许多错误的按键让你失去前进的机会:D',
    'Unlocked Drinking!': '喝已解锁!',
    'Unlocked Eating!': '吃已解锁!',
    'Unlocked Thinking!': '思考已解锁!',
    'Unlocked Game deving!': '游戏开发已解锁!',
    'Unlocked Question asking!': '问答已解锁!',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Color: ": "颜色: ",
    "Type: ": "类型: ",
    "XP: ": "经验: ",
    "XP/sec: ": "经验/秒: ",
    "Unlock text: ": "解锁文本: ",
    "Hint: ": "暗示：",
    "Skill Type: ": "技能类型: ",
    "XP%: ": "经验%: ",
    "Stars: ": "星星: ",
    "Equip": "装备",
    "equiped": "已装备",
    "Evolving": "进化",
    "reroll prefix ": "冲洗前缀",
    "reroll suffix ": "冲洗后缀",
    "thats a long one :": "这是一个很长的问题:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^rgb\(([\d\.,]+)$/,
    /^(\d+)\/(\d+)$/,
    /^([\d\.]+)$/,
    /^经验%: ([\d\.]+)$/,
    /^经验: (.+)\/(.+)/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Automate \((\d+) thinking$/, '自动 \($1 思考'],
    [/^Upgrade \((\d+) growing$/, '升级 \($1 生长'],
    [/^Enchance \((\d+) researching$/, '魅力（$1 研究'],
    [/^Evolve \((\d+) not dying$/, '进化（$1 求生欲'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);