/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Drink': '喝',
    'Grow': '生长',
    'Basic': '基础',
    'Building': '建造',
    'Eat': '吃',
    'Eating': '吃',
    'Crafting': '制作',
    'Equipping': '装备',
    'Upg item(-xp forge': '升级项目（-经验 锻造',
    'Upg prefix(-xp forge': '升级前缀（-经验 锻造',
    'Craft (-xp forge': '制作（-经验 锻造',
    'Build (-xp gather': '建造 (-经验 收集',
    'Reclaim (-xp absorb': '回收 (-经验 吸收',
    'Upg suffix(-xp forge': '升级后缀(-经验 锻造',
    'Understanding': '理解',
    'Training': '训练',
    'Train': '训练',
    'Think': '思考',
    'Thinking': '思考',
    'Total level': '总计级数',
    'Skilling': '技能',
    'Sleeping': '睡觉',
    'Selecting': '选择',
    'Hovering': '悬停',
    'Idling': '放置',
    'Importing': '导入',
    'Exporting': '导出',
    'Items': '项目',
    'Kill': '杀死',
    'Killing': '杀死',
    'Learning': '学习',
    'Level Uping': '等级提升',
    'Levels': '等级',
    'Load': '加载',
    'Loading': '加载',
    'Autoclick': '自动点击',
    'Autoclicking': '自动点击',
    'Assimilating': '同化',
    'advanced': '高级',
    'achievement': '成就',
    'Accelerate': '加速',
    'Accelerating': '加速',
    'Collecting': '收集',
    'Clicking': '点击',
    'basic': '基础',
    'Upgrading': '升级',
    'Upsizing': '升迁',
    'Reclaiming': '回收',
    'Family Acquiring': '家庭获取',
    'Gathering': '收集',
    'Gather': '收集',
    'Game deving': '游戏开发',
    'Forging': '锻造',
    'nothing': '什么都没有',
    'Perceiving': '感知',
    'Options': '选项',
    'Piece of slime': '一块史莱姆',
    'Reset (': '重置 (',
    'Researching': '研究',
    'Show XP/sec': '显示 经验/秒',
    'Show raw XP values': '显示原始经验值',
    'wisdoming': '智慧',
    'Wis-ing': '智慧',
    'ultimate': '最终',
    'Observing': '观察',
    'Not Dying': '不死',
    'Mine': '采矿',
    'Mining': '采矿',
    'athematising': '无神论',
    'Mathematise!': '数学化！',
    'Long Item Naming': '长项目命名',
    'Learn (-xp think': '学习 (-经验 思考',
    'Item autoclick': '项目自动点击',
    'Item upgrading': '项目升级',
    'Int-ing': '洞察',
    'Insight Collecting': '洞察收集',
    'Increase Efficiency': '提高效率',
    'Mathematising': '数学化',
    'More optioning': '更多选项',
    'Resetting': '重置',
    'resetting': '重置',
    'Saving': '保存',
    'strengthing': '强化',
    'Str-ing': '强化',
    'Absorbing': '吸收',
    'Achieves': '实现',
    'Achieving': '实现',
    'Acquire Family': '实现家庭',
    'ANSWER': '回答',
    'Automating': '自动',
    'backup your files': '备份文件',
    'constitutioning': '章程',
    'Con-ing': '章程',
    'craft': '制作',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Show % XP values': '按％显示经验值',
    'Should i wait to reset?': '我应该等待重置吗？',
    'what is the most famous cheat code of all time?': '有史以来最著名的作弊代码是什么？',
    'What does the \'?\' button do?': ' “？”按钮是干什么的？',
    'What does saving do?': '保存有什么用？',
    'What does reset do?': '重置有什么作用？',
    'Why so much clicking?': '为什么点击那么多？',
    'Why is one of my bars yellow?': '为什么有的进度条是黄色的？',
    'Why is game deving always 0?': '为什么游戏开发始终为0？',
    'Why is eating going down?': '为什么进食减少？',
    'well, you dont have a question selected, so no answer': '好吧，您没有选择问题，所以没有答案',
    'What does accelerating do?': '加速是做什么的？',
    'How do i level understanding?': '我该如何理解等级？',
    'How do i win?': '我怎么赢？',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Color: ": "颜色: ",
    "Type: ": "类型: ",
    "XP: ": "经验: ",
    "XP/sec: ": "经验/秒: ",
    "Unlock text: ": "解锁文本: ",
    "Hint: ": "暗示：",
    "Skill Type: ": "技能类型: ",
    "XP%: ": "经验%: ",
    "Stars: ": "星星: ",
    "Equip": "装备",
    "equiped": "已装备",
    "Evolving": "进化",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^rgb\(([\d\.,]+)$/,
    /^(\d+)\/(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Automate \((\d+) thinking$/, '自动 \($1 思考'],
    [/^Upgrade \((\d+) growing$/, '升级 \($1 生长'],
    [/^Enchance \((\d+) researching$/, '魅力（$1 研究'],
    [/^Evolve \((\d+) not dying$/, '进化（$1 不死'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);